/**
 * Created by Durzo on 6/1/2016.
 */

module.exports = {
    TOP_CONTENT_REPLACE: "[[[TOP_CONTENT_REPLACE]]]",
    MID_CONTENT_REPLACE: "[[[MID_CONTENT_REPLACE]]]",
    BOTTOM_CONTENT_REPLACE: "[[[BOTTOM_CONTENT_REPLACE]]]",
    TOP_CONTENT: "[[[TOP_CONTENT_PLACEHOLDER]]]",
    MID_CONTENT: "[[[MID_CONTENT_PLACEHOLDER]]]",
    BOTTOM_CONTENT: "[[[BOTTOM_CONTENT_PLACEHOLDER]]]",
    TOP_CONTENT_DONE: "[[[/TOP_CONTENT_PLACEHOLDER]]]",
    MID_CONTENT_DONE: "[[[/MID_CONTENT_PLACEHOLDER]]]",
    BOTTOM_CONTENT_DONE: "[[[/BOTTOM_CONTENT_PLACEHOLDER]]]"
};